"""
Comprehensive Multi-Dimensional QC Engine & Semantic Analyzer
Evaluates:
1. Semantic Quality: Incomplete fragments, hanging genitives, suspicious translation anomalies
2. ASR Script Quality: Bengali Unicode validity (\u0980–\u09FF), confidence scores
3. Non-Speech & Hallucination: Captions over silence/music, non-speech cue validity
4. Timing Quality: CPS limits (<=20), minimum duration (>=1.0s), cue overlaps, shot cuts
5. Diarization Quality: Speaker stability, speaker ID attribution
6. Quantitative Explainable Quality Score derived strictly from empirical measurements
"""

import os
import re
import json
import logging
from typing import List, Dict, Any, Tuple
from dataclasses import dataclass, asdict

logger = logging.getLogger(__name__)

# Known suspicious phonetic artifacts or hallucination tokens in English translation
SUSPICIOUS_EN_TOKENS = {"bluet", "noody", "japa", "khana", "rajthani", "chillam", "kurlao", "aswongi"}

# Bengali incomplete tokens / hanging particles
BENGALI_HANGING_TOKENS = {"এই", "এর", "র", "ও", "থেকে", "দিয়ে", "জন্য", "হলো", "এবং", "কিন্তু"}

# Hindi/Urdu grammatical markers transcribed into Bengali script (Language Mismatch)
HINDI_PHONETIC_MARKERS_IN_BENGALI = {
    "হে", "হো", "থা", "থি", "থে", "সাথ", "সে", "মে", "পর", "অউর",
    "ইয়ে", "ওহ", "ইস", "উস", "সাকতে", "রাহি", "রাহা", "রাহে", "লোগ", "লোগো",
    "আপ", "হাম", "হামারা", "তুম", "কিউ", "কাহাঁ", "কাহা", "নহি", "নহী", "বহত",
    "কেয়া", "মুজাহিদিন", "হুকুম", "খিলাফত"
}

@dataclass
class QCIssue:
    """Actionable Quality Control Issue"""
    time: str
    severity: str         # "critical", "high", "medium", "low"
    type: str             # Specific failure category code
    description: str      # Concise issue summary
    evidence: str         # Measured empirical evidence
    suggested_action: str # Actionable operator remedy

@dataclass
class QCReport:
    """Quantitative Quality Control Report with Full-Video Coverage"""
    total_cues: int
    asr_score: float
    timing_score: float
    translation_score: float
    diarization_score: float
    non_speech_score: float
    coverage_score: float
    source_duration: float
    processed_duration: float
    coverage_ratio: float
    overall_quality_score: float
    issues: List[Dict[str, Any]]

class QCReporter:
    """
    Quality Control Analyzer & Review Queue Prioritizer.
    """

    def __init__(self, config=None):
        self.config = config

    def _fmt_time(self, seconds: float) -> str:
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        s = seconds % 60
        sec = int(s)
        ms = int(round((s - sec) * 1000))
        if ms >= 1000:
            sec += 1
            ms = 0
        return f"{h:02d}:{m:02d}:{sec:02d}.{ms:03d}"

    def analyze(self,
                bn_cues: List[Dict[str, Any]],
                en_cues: List[Dict[str, Any]] = None,
                hi_cues: List[Dict[str, Any]] = None,
                silence_regions: List[Dict[str, Any]] = None,
                shot_times: List[float] = None,
                source_duration: float = 0.0,
                processed_duration: float = 0.0) -> QCReport:
        """
        Perform exhaustive multi-dimension QC analysis across all cues and duration integrity.
        """
        issues: List[QCIssue] = []
        total_cues = len(bn_cues)
        en_cues = en_cues or []
        hi_cues = hi_cues or []
        silence_regions = silence_regions or []
        shot_times = shot_times or []

        if total_cues == 0:
            return QCReport(
                total_cues=0,
                asr_score=0.0,
                timing_score=0.0,
                translation_score=0.0,
                diarization_score=0.0,
                non_speech_score=0.0,
                coverage_score=0.0,
                source_duration=source_duration,
                processed_duration=processed_duration,
                coverage_ratio=0.0,
                overall_quality_score=0.0,
                issues=[{
                    "time": "00:00:00.000",
                    "severity": "critical",
                    "type": "NO_CAPTIONS_GENERATED",
                    "description": "Zero subtitle cues were generated by pipeline",
                    "evidence": "Total cue count is 0",
                    "suggested_action": "Check audio stream presence and VAD threshold"
                }]
            )

        # Metrics counters for quantitative scoring
        asr_penalties = 0.0
        timing_penalties = 0.0
        translation_penalties = 0.0
        diarization_penalties = 0.0
        nonspeech_penalties = 0.0

        for i, cue in enumerate(bn_cues):
            st = cue['start_time']
            et = cue['end_time']
            dur = max(0.1, et - st)
            raw_text = cue.get('raw_text', cue['text']).strip()
            spk = cue['speaker']
            conf = cue.get('confidence', 0.85)
            time_str = self._fmt_time(st)

            # ── 1. NON-SPEECH & SILENCE HALLUCINATION CHECK ──
            if cue.get('type') == 'dialogue':
                for sil in silence_regions:
                    sil_st, sil_et = sil.get('start', 0.0), sil.get('end', 0.0)
                    # Check if cue is inside silence window
                    if st >= sil_st and et <= sil_et:
                        nonspeech_penalties += 25.0
                        issues.append(QCIssue(
                            time=time_str,
                            severity="critical",
                            type="HALLUCINATION_OVER_SILENCE",
                            description="Dialogue caption generated during silent audio region",
                            evidence=f"Cue [{time_str}] inside silence window [{self._fmt_time(sil_st)} - {self._fmt_time(sil_et)}]",
                            suggested_action="Discard hallucinated cue or tune VAD silence threshold"
                        ))

            # ── 2. ASR QUALITY & SCRIPT VALIDATION ──
            if cue.get('type') == 'dialogue':
                bn_chars = sum(1 for c in raw_text if '\u0980' <= c <= '\u09FF')
                bn_ratio = bn_chars / max(1, len(raw_text.replace(" ", "")))

                if bn_ratio < 0.40 and not re.search(r'[a-zA-Z]{3,}', raw_text):
                    asr_penalties += 20.0
                    issues.append(QCIssue(
                        time=time_str,
                        severity="high",
                        type="WRONG_SCRIPT",
                        description="Caption text does not contain valid Bengali Unicode script",
                        evidence=f"Bengali Unicode ratio: {bn_ratio*100:.1f}%. Text: '{raw_text[:35]}'",
                        suggested_action="Verify ASR language model decoding configuration"
                    ))
                elif conf < 0.60:
                    asr_penalties += 10.0
                    issues.append(QCIssue(
                        time=time_str,
                        severity="medium",
                        type="LOW_CONFIDENCE_ASR",
                        description="ASR acoustic confidence score below quality threshold",
                        evidence=f"Confidence: {conf:.2f} (expected >= 0.60)",
                        suggested_action="Human operator review recommended for speech clarity"
                    ))

                # Check for Hindi/Urdu dialogue transliterated into Bengali script (Language Mismatch)
                words = set(raw_text.split())
                found_hindi = words.intersection(HINDI_PHONETIC_MARKERS_IN_BENGALI)
                if len(found_hindi) >= 2 or (len(found_hindi) >= 1 and any(tok in {"হে", "হো", "থা", "থি", "থে", "মে", "সে"} for tok in found_hindi)):
                    asr_penalties += 35.0
                    issues.append(QCIssue(
                        time=time_str,
                        severity="high",
                        type="LANGUAGE_MISMATCH_HINDI_IN_BENGALI",
                        description="Audio appears to be Hindi/Urdu dialogue phonetically captured into Bengali script",
                        evidence=f"Found Hindi grammatical markers: {sorted(list(found_hindi))}",
                        suggested_action="Route segment through Indic multilingual ASR with Hindi tag"
                    ))

            # ── 3. SEMANTIC FRAGMENT DETECTION ──
            if cue.get('type') == 'dialogue':
                tokens = raw_text.split()
                # Check for hanging genitives or incomplete grammatical endings
                last_token = tokens[-1] if tokens else ""
                if last_token in BENGALI_HANGING_TOKENS or (len(tokens) <= 2 and dur < 1.1 and not re.search(r'[।!?]', raw_text)):
                    asr_penalties += 8.0
                    issues.append(QCIssue(
                        time=time_str,
                        severity="medium",
                        type="INCOMPLETE_FRAGMENT",
                        description="Caption appears to be a fragmented sentence or hanging phrase",
                        evidence=f"Phrase '{raw_text}' ends with particle '{last_token}' without terminal punctuation",
                        suggested_action="Merge with adjacent cue or adjust ASR segmentation window"
                    ))

            # ── 4. TIMING & CPS VALIDATION ──
            if cue.get('type') == 'dialogue':
                cps = len(raw_text) / dur
                if cps > 20.0:
                    timing_penalties += 15.0
                    issues.append(QCIssue(
                        time=time_str,
                        severity="high" if cps > 26.0 else "medium",
                        type="CPS_VIOLATION",
                        description="Reading speed exceeds broadcast timed-text limits",
                        evidence=f"CPS: {cps:.1f} chars/sec (limit: 20.0). Length: {len(raw_text)} chars in {dur:.2f}s",
                        suggested_action="Extend cue display duration or split into two cues"
                    ))

                if dur < 0.8:
                    timing_penalties += 6.0
                    issues.append(QCIssue(
                        time=time_str,
                        severity="low",
                        type="SHORT_DURATION",
                        description="Cue duration below broadcast minimum readability threshold",
                        evidence=f"Duration: {dur:.2f}s (broadcast minimum: 0.80s)",
                        suggested_action="Pad cue end boundary to allow viewers time to read"
                    ))

            # Check Cue Overlap
            if i < total_cues - 1:
                next_st = bn_cues[i+1]['start_time']
                if et > next_st + 0.02:
                    timing_penalties += 12.0
                    issues.append(QCIssue(
                        time=time_str,
                        severity="medium",
                        type="CUE_OVERLAP",
                        description="Cue timestamp overlaps with subsequent cue start",
                        evidence=f"Ends at {self._fmt_time(et)} but next cue starts at {self._fmt_time(next_st)}",
                        suggested_action="Adjust cue end boundary to prevent on-screen collision"
                    ))

            # Check Shot Boundary Straddling
            for cut in shot_times:
                if st + 0.3 < cut < et - 0.3:
                    timing_penalties += 4.0
                    issues.append(QCIssue(
                        time=time_str,
                        severity="low",
                        type="SHOT_STRADDLE",
                        description="Subtitle cue straddles across a camera shot cut",
                        evidence=f"Shot cut detected at {self._fmt_time(cut)} inside cue [{time_str} - {self._fmt_time(et)}]",
                        suggested_action="Align cue boundary to camera cut transition"
                    ))

            # ── 5. TRANSLATION & SEMANTIC ANOMALY VALIDATION ──
            if en_cues and i < len(en_cues):
                en_text = en_cues[i].get('text', '').strip()
                has_bengali_in_en = any('\u0980' <= c <= '\u09FF' for c in en_text)
                if cue.get('type') == 'dialogue' and (en_text == raw_text or en_text == "[Translation Unavailable]" or has_bengali_in_en):
                    translation_penalties += 25.0
                    issues.append(QCIssue(
                        time=time_str,
                        severity="high",
                        type="UNTRANSLATED_SOURCE",
                        description="English track contains untranslated raw Bengali text or translation failure",
                        evidence=f"English text contains Bengali or failure: '{en_text[:35]}'",
                        suggested_action="Verify translation API connectivity and retranslate cue"
                    ))
                elif not en_text:
                    translation_penalties += 25.0
                    issues.append(QCIssue(
                        time=time_str,
                        severity="critical",
                        type="EMPTY_TRANSLATION",
                        description="English subtitle track cue is empty",
                        evidence=f"Source: '{raw_text}' yielded empty translation",
                        suggested_action="Trigger re-translation for segment"
                    ))
                else:
                    # Semantic anomaly check for suspicious transliteration tokens
                    lower_en = en_text.lower()
                    for token in SUSPICIOUS_EN_TOKENS:
                        if token in lower_en:
                            translation_penalties += 8.0
                            issues.append(QCIssue(
                                time=time_str,
                                severity="high",
                                type="SEMANTIC_ANOMALY",
                                description="Suspicious phonetic artifact or transliteration detected in translation",
                                evidence=f"Found artifact token '{token}' in English subtitle: '{en_text}'",
                                suggested_action="Review segment audio for code-switching or terminology correction"
                            ))
                            break

            # ── 6. DIARIZATION STABILITY CHECK ──
            if i > 0 and bn_cues[i-1]['speaker'] != spk and (st - bn_cues[i-1]['start_time']) < 1.2:
                diarization_penalties += 5.0
                issues.append(QCIssue(
                    time=time_str,
                    severity="low",
                    type="RAPID_SPEAKER_SWITCH",
                    description="Rapid speaker attribution change within 1.2 seconds",
                    evidence=f"Switched from {bn_cues[i-1]['speaker']} to {spk} across {st - bn_cues[i-1]['start_time']:.2f}s",
                    suggested_action="Verify acoustic turn boundary"
                ))

        # ── 7. FULL-DURATION COVERAGE & INTEGRITY CHECK ──
        last_cue_time = bn_cues[-1]['end_time'] if bn_cues else 0.0
        if source_duration > 0.0:
            coverage_ratio = round(min(1.0, last_cue_time / max(1.0, source_duration)), 3)
            # If duration is long (> 60s) and coverage is below 85%
            if source_duration >= 60.0 and coverage_ratio < 0.85:
                issues.append(QCIssue(
                    time=self._fmt_time(last_cue_time),
                    severity="critical",
                    type="INCOMPLETE_VIDEO_COVERAGE",
                    description=f"Subtitle generation ceased before video end: {coverage_ratio*100:.1f}% coverage",
                    evidence=f"Source duration is {self._fmt_time(source_duration)}, but last subtitle is at {self._fmt_time(last_cue_time)}",
                    suggested_action="Investigate ffmpeg extraction timeout or chunking truncation"
                ))
        else:
            coverage_ratio = 1.0
            source_duration = last_cue_time
            processed_duration = last_cue_time

        coverage_score = round(coverage_ratio * 100.0, 1)

        # ── 8. CALCULATE EXPLAINABLE COMPONENT SCORES ──
        asr_score = max(0.0, min(100.0, 100.0 - (asr_penalties / max(1, total_cues)) * 10.0))
        timing_score = max(0.0, min(100.0, 100.0 - (timing_penalties / max(1, total_cues)) * 10.0))
        translation_score = max(0.0, min(100.0, 100.0 - (translation_penalties / max(1, total_cues)) * 10.0))
        nonspeech_score = max(0.0, min(100.0, 100.0 - (nonspeech_penalties / max(1, total_cues)) * 10.0))
        diarization_score = max(50.0, min(100.0, 95.0 - (diarization_penalties / max(1, total_cues)) * 10.0))

        # Weighted composite score across all 6 dimensions
        overall = (
            0.30 * asr_score +
            0.20 * timing_score +
            0.20 * translation_score +
            0.10 * nonspeech_score +
            0.10 * diarization_score +
            0.10 * coverage_score
        )
        overall_quality_score = round(max(0.0, min(100.0, overall)), 1)

        # Rank issues by severity order: critical > high > medium > low
        sev_rank = {"critical": 0, "high": 1, "medium": 2, "low": 3}
        issue_dicts = [asdict(iss) for iss in issues]
        issue_dicts.sort(key=lambda x: (sev_rank.get(x["severity"], 3), x["time"]))

        logger.info(f"QC: Analyzed {total_cues} cues → {len(issues)} issues detected. Score: {overall_quality_score}")

        return QCReport(
            total_cues=total_cues,
            asr_score=round(asr_score, 1),
            timing_score=round(timing_score, 1),
            translation_score=round(translation_score, 1),
            diarization_score=round(diarization_score, 1),
            non_speech_score=round(nonspeech_score, 1),
            coverage_score=coverage_score,
            source_duration=round(source_duration, 2),
            processed_duration=round(processed_duration, 2),
            coverage_ratio=coverage_ratio,
            overall_quality_score=overall_quality_score,
            issues=issue_dicts
        )